"""
seed_database.py

Fills enterprise.db with realistic sample data so that SQL queries
generated by a text-to-SQL model can actually be *executed* and
compared (execution_match), not just checked syntactically.

Run create_database.py first.

Usage:
    python seed_database.py
"""

import sqlite3
import random
from datetime import date, timedelta

DB_PATH = "enterprise.db"
random.seed(42)  # reproducible data

# ---------------------------------------------------------------------
# Reference pools used to generate realistic-looking rows
# ---------------------------------------------------------------------

FIRST_NAMES = ["Ahmed", "Sara", "Omar", "Mona", "Youssef", "Laila", "Hassan",
               "Nour", "Karim", "Dina", "Tarek", "Heba", "Mostafa", "Salma",
               "Adel", "Rania", "Amr", "Yasmin", "Khaled", "Farida"]
LAST_NAMES = ["Ibrahim", "Mahmoud", "El-Sayed", "Hassan", "Abdel Rahman",
              "Fathy", "Nour El-Din", "Saad", "Kamel", "Farouk"]
CITIES_COUNTRIES = [
    ("Cairo", "Egypt"), ("Giza", "Egypt"), ("Alexandria", "Egypt"),
    ("Dubai", "UAE"), ("Riyadh", "Saudi Arabia"), ("Amman", "Jordan"),
    ("Beirut", "Lebanon"), ("Doha", "Qatar"), ("Casablanca", "Morocco"),
    ("Tunis", "Tunisia"),
]
CATEGORY_NAMES = ["Electronics", "Groceries", "Clothing", "Furniture",
                   "Toys", "Books", "Sports", "Beauty"]
SUPPLIER_NAMES = ["Nile Trading Co", "Delta Supplies", "Pyramid Distributors",
                   "Red Sea Imports", "Sahara Wholesale", "Cairo Goods Ltd"]
PRODUCT_ADJECTIVES = ["Premium", "Classic", "Deluxe", "Essential", "Pro",
                       "Compact", "Standard", "Advanced"]
PRODUCT_NOUNS = ["Blender", "Laptop", "Jacket", "Sofa", "Puzzle", "Novel",
                  "Football", "Lotion", "Headphones", "Backpack", "Lamp",
                  "Watch", "Kettle", "Desk", "Sneakers"]
EMPLOYEE_TITLES = ["Sales Rep", "Account Manager", "Support Agent",
                    "Warehouse Lead", "Regional Manager"]
SHIPPER_NAMES = ["Speedy Logistics", "Nile Express", "Fast Track Shipping",
                  "Desert Courier"]
PAYMENT_METHODS = ["Credit Card", "Cash on Delivery", "Bank Transfer",
                    "Mobile Wallet"]
PAYMENT_STATUSES = ["Completed", "Pending", "Failed", "Refunded"]
ORDER_STATUSES = ["Pending", "Shipped", "Delivered", "Cancelled"]
WAREHOUSES = ["Cairo Warehouse", "Alexandria Warehouse", "Giza Warehouse"]


def random_date(start: date, end: date) -> date:
    delta = (end - start).days
    return start + timedelta(days=random.randint(0, delta))


def seed_database(db_path: str = DB_PATH,
                   n_customers: int = 50,
                   n_products: int = 40,
                   n_orders: int = 120) -> None:
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute("PRAGMA foreign_keys = ON;")

    today = date(2026, 8, 5)
    three_years_ago = today - timedelta(days=3 * 365)

    # --- Customers -----------------------------------------------------
    customers = []
    for cid in range(1, n_customers + 1):
        fn, ln = random.choice(FIRST_NAMES), random.choice(LAST_NAMES)
        city, country = random.choice(CITIES_COUNTRIES)
        name = f"{fn} {ln}"
        email = f"{fn.lower()}.{ln.lower().replace(' ', '')}{cid}@example.com"
        phone = f"+2010{random.randint(10000000, 99999999)}"
        created_at = random_date(three_years_ago, today)
        customers.append((cid, name, email, phone, city, country, created_at.isoformat()))
    cur.executemany(
        "INSERT INTO Customers VALUES (?,?,?,?,?,?,?)", customers
    )

    # --- Addresses (1-2 per customer) -----------------------------------
    addresses = []
    addr_id = 1
    for cid, *_ in customers:
        for _ in range(random.randint(1, 2)):
            city, country = random.choice(CITIES_COUNTRIES)
            addresses.append((
                addr_id, cid, f"{random.randint(1, 200)} {random.choice(LAST_NAMES)} St",
                city, city, f"{random.randint(10000, 99999)}", country
            ))
            addr_id += 1
    cur.executemany("INSERT INTO Addresses VALUES (?,?,?,?,?,?,?)", addresses)

    # --- Categories ------------------------------------------------------
    categories = [(i + 1, name) for i, name in enumerate(CATEGORY_NAMES)]
    cur.executemany("INSERT INTO Categories VALUES (?,?)", categories)

    # --- Suppliers ---------------------------------------------------------
    suppliers = []
    for i, name in enumerate(SUPPLIER_NAMES, start=1):
        _, country = random.choice(CITIES_COUNTRIES)
        suppliers.append((i, name, country))
    cur.executemany("INSERT INTO Suppliers VALUES (?,?,?)", suppliers)

    # --- Products ----------------------------------------------------------
    products = []
    for pid in range(1, n_products + 1):
        name = f"{random.choice(PRODUCT_ADJECTIVES)} {random.choice(PRODUCT_NOUNS)}"
        category_id = random.randint(1, len(categories))
        supplier_id = random.randint(1, len(suppliers))
        price = round(random.uniform(5, 2000), 2)
        stock = random.randint(0, 500)
        discontinued = 1 if random.random() < 0.1 else 0
        products.append((pid, name, category_id, supplier_id, price, stock, discontinued))
    cur.executemany("INSERT INTO Products VALUES (?,?,?,?,?,?,?)", products)

    # --- Employees -----------------------------------------------------------
    employees = []
    for eid in range(1, 11):
        fn, ln = random.choice(FIRST_NAMES), random.choice(LAST_NAMES)
        title = random.choice(EMPLOYEE_TITLES)
        hire_date = random_date(three_years_ago, today)
        employees.append((eid, fn, ln, title, hire_date.isoformat()))
    cur.executemany("INSERT INTO Employees VALUES (?,?,?,?,?)", employees)

    # --- Shippers -------------------------------------------------------------
    shippers = [(i + 1, name, f"+2011{random.randint(10000000, 99999999)}")
                for i, name in enumerate(SHIPPER_NAMES)]
    cur.executemany("INSERT INTO Shippers VALUES (?,?,?)", shippers)

    # --- Payments (one per order, created below then linked) -----------------
    payments = []
    for pay_id in range(1, n_orders + 1):
        method = random.choice(PAYMENT_METHODS)
        pay_date = random_date(three_years_ago, today)
        status = random.choice(PAYMENT_STATUSES)
        payments.append((pay_id, method, pay_date.isoformat(), status))
    cur.executemany("INSERT INTO Payments VALUES (?,?,?,?)", payments)

    # --- Orders + Order_Items -----------------------------------------------
    orders = []
    order_items = []
    oi_id = 1
    for oid in range(1, n_orders + 1):
        customer_id = random.randint(1, n_customers)
        employee_id = random.randint(1, len(employees))
        shipper_id = random.randint(1, len(shippers))
        payment_id = oid  # 1-to-1 with payments created above
        order_date = random_date(three_years_ago, today)
        status = random.choice(ORDER_STATUSES)
        if status in ("Shipped", "Delivered"):
            shipped_date = order_date + timedelta(days=random.randint(1, 10))
            shipped_date_val = shipped_date.isoformat()
        else:
            shipped_date_val = None

        # order items for this order
        n_items = random.randint(1, 5)
        chosen_products = random.sample(range(1, n_products + 1), n_items)
        total_amount = 0.0
        for product_id in chosen_products:
            quantity = random.randint(1, 10)
            unit_price = next(p[4] for p in products if p[0] == product_id)
            discount = round(random.choice([0, 0, 0, 0.05, 0.1, 0.15]), 2)
            line_total = quantity * unit_price * (1 - discount)
            total_amount += line_total
            order_items.append((oi_id, oid, product_id, quantity, unit_price, discount))
            oi_id += 1

        orders.append((
            oid, customer_id, employee_id, shipper_id, payment_id,
            order_date.isoformat(), shipped_date_val, status, round(total_amount, 2)
        ))

    cur.executemany("INSERT INTO Orders VALUES (?,?,?,?,?,?,?,?,?)", orders)
    cur.executemany("INSERT INTO Order_Items VALUES (?,?,?,?,?,?)", order_items)

    # --- Inventory (per product, across warehouses) ---------------------------
    inventory = []
    inv_id = 1
    for product_id, *_ in [(p[0],) for p in products]:
        for warehouse in random.sample(WAREHOUSES, k=random.randint(1, len(WAREHOUSES))):
            inventory.append((inv_id, product_id, warehouse, random.randint(0, 300)))
            inv_id += 1
    cur.executemany("INSERT INTO Inventory VALUES (?,?,?,?)", inventory)

    # --- Reviews ----------------------------------------------------------------
    reviews = []
    rev_id = 1
    for product_id in range(1, n_products + 1):
        for _ in range(random.randint(0, 6)):
            customer_id = random.randint(1, n_customers)
            rating = random.randint(1, 5)
            review_date = random_date(three_years_ago, today)
            reviews.append((rev_id, product_id, customer_id, rating, review_date.isoformat()))
            rev_id += 1
    cur.executemany("INSERT INTO Reviews VALUES (?,?,?,?,?)", reviews)

    conn.commit()

    # quick summary
    for table in ["Customers", "Addresses", "Categories", "Suppliers", "Products",
                  "Employees", "Shippers", "Payments", "Orders", "Order_Items",
                  "Inventory", "Reviews"]:
        count = cur.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        print(f"  {table:<15} {count} rows")

    conn.close()
    print(f"[OK] Seeded '{db_path}'.")


if __name__ == "__main__":
    seed_database()
